sitemap_urls:
  - "https://www.legit.ng/legit/sitemap/www/sitemap.xml"

custom_settings:
  SELENIUM_DRIVER_NAME: "chrome"
  SELENIUM_DRIVER_EXECUTABLE_PATH: "/Users/theyorubayesian/Downloads/chromedriver"
  JOBDIR: "crawls/new_legitng_spider"
  RESTART_INDICATOR: "legitng.restart"
  CONCURRENT_REQUESTS: 1
  CLOSESPIDER_ITEMCOUNT: 20
  OUTPUT_FILE: "data/new_legitng_english.jsonl"
  DOWNLOADER_MIDDLEWARES:
    otelemuye.middlewares.SeleniumMiddleware: 543
  ITEM_PIPELINES:
    otelemuye.pipelines.JsonWriterPipeline: 300